### ISSUE TITLE
Allow configuring Docker image Database 

### ISSUE THREAD

**Issue by xShteff** [veertuinc/anklet#35]
Hello there. Right now the docker image can allow configuring the database credentials for the metrics, but not anything else. 

https://github.com/veertuinc/anklet/blob/main/docker/docker-compose.yml#L33

```yaml
# - ANKLET_METRICS_DATABASE_URL=host.docker.internal
# - ANKLET_METRICS_DATABASE_PORT=6379
# - ANKLET_METRICS_DATABASE_USER=
# - ANKLET_METRICS_DATABASE_PASSWORD=
# - ANKLET_METRICS_DATABASE_DATABASE=0
```

Would it be possible to introduce the possibility of a `ANKLET_GLOBAL_DATABASE_[USER | PASSWORD | DATABASE | PORT]`, so that both the GitHub handler and metrics use the same database? (we're primairly interested in being able to configure the database for the GitHub Handler tho')

**Comment by NorseGaud** [comment]
Released in 0.8.0
